# Generated by Django 5.0.3 on 2025-04-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0002_alter_result_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
