# Generated by Django 5.0.3 on 2025-05-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
