# Generated by Django 5.0.3 on 2025-05-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0004_alter_result_month'),
        ('Core_app', '0006_alter_result_rating'),
    ]

    operations = [
    ]
